require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.4

Naming/FileName:
  Exclude:
    - 'lib/sensu-plugins-foreman.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20
